### ISSUE TITLE
Failed to add repository, how to debug ?

### ISSUE THREAD

**Issue by augu5te** [nix-community/NUR#166]
I try to add [nur-kapack](https://github.com/oar-team/nur-kapack) repository to nur. The repo is based on nur-template and travis build is succesfull ([travis build](https://travis-ci.com/oar-team/nur-kapack)). The CI on NUR failed (pull request #165) with the following error.  I don't know  how to address this issue. Is it a simple one ?

```
[0.0 MiB DL]
INFO:nur.update:Evaluate repository kapack
error: while evaluating anonymous function at /nix/store/qvzj27il1373gki369jm3zg2vzr9xg69-nixpkgs-20.03pre204216.cc6cf0a96a6/nixpkgs/pkgs/build-support/replace-dependency.nix:20:1, called from /nix/store/2x2q6y0rps9sml7ff0z3g80k2za55f6h-source/default.nix:65:14:
cannot import '/nix/store/rp3n56hnxp85widn75hlj08f9gbk4yp2-references.nix', since path '/nix/store/6nkfqg35rr5if36lm9lzz8bdvb9fsc98-references.nix.drv' is not valid, at /nix/store/qvzj27il1373gki369jm3zg2vzr9xg69-nixpkgs-20.03pre204216.cc6cf0a96a6/nixpkgs/pkgs/build-support/replace-dependency.nix:26:16
Traceback (most recent call last):
  File "/nix/store/kcr2j1z281i3mdg5wczp4w6w8dh3g17x-nur/bin/.nur-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/kcr2j1z281i3mdg5wczp4w6w8dh3g17x-nur/lib/python3.7/site-packages/nur/__init__.py", line 58, in main
    args.func(args)
  File "/nix/store/kcr2j1z281i3mdg5wczp4w6w8dh3g17x-nur/lib/python3.7/site-packages/nur/update.py", line 80, in update_command
    update(repo)
  File "/nix/store/kcr2j1z281i3mdg5wczp4w6w8dh3g17x-nur/lib/python3.7/site-packages/nur/update.py", line 67, in update
    eval_repo(repo, repo_path)
  File "/nix/store/kcr2j1z281i3mdg5wczp4w6w8dh3g17x-nur/lib/python3.7/site-packages/nur/update.py", line 60, in eval_repo
    raise EvalError(f"{repo.name} does not evaluate:\n$ {' '.join(cmd)}")
nur.error.EvalError: kapack does not evaluate:
$ nix-env -f /tmp/tmpmjho3l12/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/qvzj27il1373gki369jm3zg2vzr9xg69-nixpkgs-20.03pre204216.cc6cf0a96a6/nixpkgs -I /nix/store/2x2q6y0rps9sml7ff0z3g80k2za55f6h-source -I /tmp/tmpmjho3l12/default.nix -I /home/travis/build/nix-community/NUR/lib/evalRepo.nix
The command "bash ci/deploy.sh" exited with 1.
```

**Comment by augu5te** [comment]
I just figured out that NUR CI does not support pkgs.replaceDependency in repo.name default.nix
