### ISSUE TITLE
NUR not updating apparently since #458

### ISSUE THREAD

**Issue by sigprof** [nix-community/NUR#461]
Looks like the update action always fails since #458 was merged:
```
ERROR:nur.update:repository bandithedoge failed to evaluate: bandithedoge does not evaluate:
$ nix-env -f /tmp/tmpmlq4qsf3/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org/ --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/zcb4pylsfrnz2dz106k2chki97grn2dg-source -I /nix/store/sk1kkqq5w0g0nzbxx6bzsy4hnp3ns013-source -I /tmp/tmpmlq4qsf3/default.nix -I /home/runner/work/NUR/NUR/lib/evalRepo.nix. This repo is not yet in our lock file!!!!
Traceback (most recent call last):
  File "/nix/store/ndiramh14pmvraq12lsk36s82m7qm5hi-nur/bin/.nur-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/ndiramh14pmvraq12lsk36s82m7qm5hi-nur/lib/python3.9/site-packages/nur/__init__.py", line 58, in main
    args.func(args)
  File "/nix/store/ndiramh14pmvraq12lsk36s82m7qm5hi-nur/lib/python3.9/site-packages/nur/update.py", line 79, in update_command
    update(repo)
  File "/nix/store/ndiramh14pmvraq12lsk36s82m7qm5hi-nur/lib/python3.9/site-packages/nur/update.py", line 66, in update
    eval_repo(repo, repo_path)
  File "/nix/store/ndiramh14pmvraq12lsk36s82m7qm5hi-nur/lib/python3.9/site-packages/nur/update.py", line 59, in eval_repo
    raise EvalError(f"{repo.name} does not evaluate:\n$ {' '.join(cmd)}")
nur.error.EvalError: bandithedoge does not evaluate:
$ nix-env -f /tmp/tmpmlq4qsf3/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org/ --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/zcb4pylsfrnz2dz106k2chki97grn2dg-source -I /nix/store/sk1kkqq5w0g0nzbxx6bzsy4hnp3ns013-source -I /tmp/tmpmlq4qsf3/default.nix -I /home/runner/work/NUR/NUR/lib/evalRepo.nix
Error: Process completed with exit code 1.
```

Looks like the code that triggers the failure is https://github.com/nix-community/NUR/blob/f378bcebe4455277d6deb118f11aaaad69db9e9a/ci/nur/update.py#L80-L86

This code treats the case when a newly added repository does not evaluate as fatal; this may be correct when CI is checking the pull request to add that repository, but probably not when running a scheduled or triggered update (in that case updating the other repositories which are not broken should probably have a priority).

**Comment by Mic92** [comment]
Ok. I will undo the commit again.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/NUR/commit/95519a158d63e6d6bdb231d7c11d529a271c6b1e
